config/routes.rb
Rails.application.routes.draw do
  devise_for :users #device機能

  root 'top#index' #top page
  get '/home/about' => 'top#about'
  get '/users/history' => 'users#history'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only:[:show, :index, :edit, :update] do
  	resource :relationships, only: [:create, :destroy]
  	get :follows, on: :member
  	get :followers, on: :member
  end

  resources :books do
  	resources :post_comments, only: [:create, :destroy, :edit, :update]
  	resource :favorites, only: [:create, :destroy]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   #名前でログイン可能にする
   def email_required?
   	  false
   end
   def email_changed?
      false
   end

   validates :name, length: {minimum: 2, maximum: 20}
   validates :introduction, length: {maximum: 50}
   attachment :profile_image
   has_many :books, dependent: :destroy
   has_many :post_comments, dependent: :destroy
   has_many :search_histories, dependent: :destroy

   #いいね機能
   has_many :favorites, dependent: :destroy

   def followed_by?(user)
     passive_relationships.find_by(following_id: user.id).present?
   end


   #follow follwer機能
   has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
   has_many :followings, through: :active_relationships, source: :follower

   has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
   has_many :followers, through: :passive_relationships, source: :following


   #検索機能
   def self.search(search, search_way)
      if search && search_way == "1"
        where(['name LIKE?', "%#{search}%"])
      elsif search && search_way == "2"
        where(['name LIKE?', "#{search}%"])
      elsif search && search_way == "3"
        where(['name LIKE?', "%#{search}"])
      elsif search && search_way == "4"
        where(name: search)
      else
        all
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!

  def show
  	@user = User.find(params[:id])
  	@book = Book.new
  	@books = @user.books
    @search_histories = @user.search_histories.all

    @follows = @user.followings
    @followers = @user.followers
  end

  def index
  	@book = Book.new
  	@users = User.all
  end

  def edit
  	@user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

  def update
  	@user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "User information was successfully updated"
       redirect_to user_path(@user.id)
    else
       render :edit
    end
  end

  def follows
    @user = User.find(params[:id])
    @following = @user.followings
  end

  def followers
    @user = User.find(params[:id])
    @followers = @user.followers
  end

  def history
    @user = current_user
    if params[:order] == "1"
      @search_histories = @user.search_histories.order("id")
    elsif params[:order] == "2"
      @search_histories = @user.search_histories.order('history')
    end
    render :history
  end



  private
	def user_params
		params.require(:user).permit(:name, :introduction, :profile_image)
	end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_recently_search.html.erb

<table class="table">
<% search_histories.each do |s| %>
	<tbody>
		<tr>
			<td><%= s.created_at %></td>
			<td><%= s.history %></td>
		</tr>
	</tbody>
<% end %>
</table>



app/views/users/edit.html.erb
<% if @user.errors.any? %>
   <h2>error</h2>
<% end %>

<h1>User info</h1>
	<%= form_for(@user) do |f| %>
<h4>Name</h4>
	<%=f.text_field :name %>
<h4>image</h4>
    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>

<h4>Introduction</h4>
	<%= f.text_field :introduction %>


	<%=f.submit 'Update User' %>
	<% end %>

app/views/users/followers.html.erb

<div class="container">
<div class="row">

<div class="col-lg-3">
	<h1>User info</h1>
	<%= attachment_image_tag current_user, :profile_image,　format: 'jpeg', size: "100x100", fallback: "img/no_image.jpg" %>
<table class="table table-striped">
	<tr>
		<th>name</th>
		<th><%= current_user.name %></th>
	</tr>
	<tr>
		<th>introduction</th>
		<th><%= current_user.introduction %></th>
	</tr>
</table>

<%= link_to "プロフィール編集", edit_user_path(current_user) %>

</div>



<div class="col-lg-9">
	<h1><%= "#{@user.name}をフォローしている人たち" %></h1>
	<table class="table">
		<tr>
			<th>image</th>
			<th>name</th>
		</tr>

<% @user.followers.each do |user| %>
		<tr>
			<th><%= attachment_image_tag user, :profile_image,　format: 'jpeg', size: "40x40", fallback: "img/no_image.jpg" %></th>
			<th><%= user.name %></th>
			<th><%=link_to "Show", user_path(user.id) %></th>

			<% if current_user != user %>
				<% if user.followed_by?(current_user) %>
				<th><p><%=link_to "フォロー済み", user_relationships_path(user.id), method: :delete, class: "btn btn-success" %></p>
				</th>
				<% else %>
				<th>
				<p><%=link_to "フォローする
				", user_relationships_path(user.id), method: :post, class: "btn btn-primary" %></p>
				</th>
				<% end %>
			<% end %>
		</tr>
<% end %>
	</table>
</div>

</div>
</div>

app/views/users/follows.html.erb
<div class="container">
<div class="row">

<div class="col-lg-3">
	<h1>User info</h1>
	<%= attachment_image_tag current_user, :profile_image,　format: 'jpeg', size: "100x100", fallback: "img/no_image.jpg" %>
<table class="table table-striped">
	<tr>
		<th>name</th>
		<th><%= current_user.name %></th>
	</tr>
	<tr>
		<th>introduction</th>
		<th><%= current_user.introduction %></th>
	</tr>
</table>

<%= link_to "プロフィール編集", edit_user_path(current_user) %>

</div>



<div class="col-lg-9">
	<h1><%= "#{@user.name}がフォローしている人たち" %></h1>
	<table class="table">
		<tr>
			<th>image</th>
			<th>name</th>
		</tr>

<% @user.followings.each do |user| %>
		<tr>
			<th><%= attachment_image_tag user, :profile_image,　format: 'jpeg', size: "40x40", fallback: "img/no_image.jpg" %></th>
			<th><%= user.name %></th>
			<th><%=link_to "Show", user_path(user.id) %></th>

			<% if current_user != user %>
				<% if user.followed_by?(current_user) %>
				<th><p><%=link_to "フォロー済み", user_relationships_path(user.id), method: :delete, class: "btn btn-success" %></p>
				</th>
				<% else %>
				<th>
				<p><%=link_to "フォローする
				", user_relationships_path(user.id), method: :post, class: "btn btn-primary" %></p>
				</th>
				<% end %>
			<% end %>
		</tr>
<% end %>
	</table>
</div>

</div>
</div>


app/views/users/history.js.erb
$("#search_history").html("<%= j(render 'recently_search', { search_histories: @search_histories }) %>")

app/views/users/index.html.erb
<div class="container">
<div class="row">

<div class="col-lg-3">
	<h1>User info</h1>
	<%= attachment_image_tag current_user, :profile_image,　format: 'jpeg', size: "100x100", fallback: "img/no_image.jpg" %>
<table class="table table-striped">
	<tr>
		<th>name</th>
		<th><%= current_user.name %></th>
	</tr>
	<tr>
		<th>introduction</th>
		<th><%= current_user.introduction %></th>
	</tr>
</table>

<%= link_to "プロフィール編集", edit_user_path(current_user) %>


<h1>New Book</h1>
	<%= form_for(@book) do |f| %>
<h4>Title</h4>
	<%=f.text_field :title %>
<h4>Opinion</h4>
	<%=f.text_area :body %> <br>

	<%=f.submit 'Create Book', class:"btn btn-primary" %>
	<% end %>

</div>



<div class="col-lg-9">
	<h1>Users</h1>
	<table class="table">
		<tr>
			<th>image</th>
			<th>name</th>
		</tr>

<% @users.each do |user| %>
		<tr>
			<th><%= attachment_image_tag user, :profile_image,　format: 'jpeg', size: "40x40", fallback: "img/no_image.jpg" %></th>
			<th><%= user.name %></th>
			<th><%=link_to "Show", user_path(user.id) %></th>
		</tr>
<% end %>
	</table>
</div>

</div>
</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
	<div class="flash">
     	<%= flash[:notice] %>
    </div>
<% end %>


<div class="container">
<div class="row">

<div class="col-lg-3">
	<h1 class="jquery">User info</h1>

	<%= attachment_image_tag @user, :profile_image,　format: 'jpeg', size: "100x100", fallback: "img/no_image.jpg" %>

<table class="table table-striped">
	<tr>
		<th>name</th>
		<th><%= @user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= @user.introduction %></th>
	</tr>

	<tr>
		<th>
			<i class="fas fa-male fa-2x"></i>
			<%= link_to "#{@user.followings.count}  Following", follows_user_path %>
		</th>
	</tr>
	<tr>
		<th>
			<i class="fas fa-male fa-2x"></i>
			<%= link_to "#{@user.followers.count} Followers", followers_user_path %>
		</th>
	</tr>
</table>

<% if @user == current_user %>
<%= link_to "プロフィール編集", edit_user_path(@user) %>
<% end %>

<% if current_user != @user %>
	<% if @user.followed_by?(current_user) %>
        <p><%=link_to "フォロー済み", user_relationships_path(@user.id), method: :delete, class: "btn btn-success" %></p>
    <% else %>
        <p><%=link_to "フォローする", user_relationships_path(@user.id), method: :post, class: "btn btn-primary" %></p>
    <% end %>
<% end %>

<h1>New Book</h1>
	<%= form_for(@book) do |f| %>
<h4>Title</h4>
	<%=f.text_field :title %>
<h4>Opinion</h4>
	<%=f.text_area :body %> <br>

	<%=f.submit 'Create Book', class:"btn btn-primary" %>
	<% end %>

</div>



<div class="col-lg-9">
	<h1>Books</h1>
	<table class="table">
		<tr>
			<th></th>
			<th>Title</th>
			<th>Opiniton</th>
		</tr>

<% @books.each do |book| %>
		<tr>
			<th><%= attachment_image_tag book.user, :profile_image,　format: 'jpeg', size: "40x40" %></th>
			<th><%=link_to book.title, book_path(book.id) %></th>
			<th><%= book.body %></th>
		</tr>
<% end %>

	</table>

	<h2>検索履歴</h2>
	<%= form_tag(users_history_path, method: :get, remote: true) do %>
	<%= select_tag 'order', options_for_select({日時で並び替え: 1, 五十音で並び替え: 2}) %>
	<%= submit_tag '並び替え' %>
	<% end %>
	<div id="search_history">
		<%= render 'recently_search', search_histories: @search_histories %>
	</div>
</div>

</div>
</div>