config/routes.rb
Rails.application.routes.draw do
  devise_for :users #device機能

  root 'top#index' #top page
  get '/home/about' => 'top#about'
  get '/users/history' => 'users#history'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only:[:show, :index, :edit, :update] do
  	resource :relationships, only: [:create, :destroy]
  	get :follows, on: :member
  	get :followers, on: :member
  end

  resources :books do
  	resources :post_comments, only: [:create, :destroy, :edit, :update]
  	resource :favorites, only: [:create, :destroy]
  end
end

app/models/book.rb
class Book < ApplicationRecord

	validates :title, presence: true, length: {maximum: 200}

	validates :body, presence: true, length: {maximum: 200}

	belongs_to :user
	has_many :post_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

	def favorited_by?(user)
        favorites.where(user_id: user.id).exists?
  end


  #books controllerのindex actionで使用
   def self.search(search, search_way)
      if search && search_way == "1"
        where(['title LIKE?', "%#{search}%"])
      elsif search && search_way == "2"
        where(['title LIKE?', "#{search}%"])
      elsif search && search_way == "3"
        where(['title LIKE?', "%#{search}"])
      elsif search && search_way == "4"
        where(title: search)
      else
        all
      end
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!

	def index
		@book = Book.new

		#search_modelの値によって、Bookを検索するかUserを検索するかが変化
		#search_wayの値によって、部分一致検索、前方一致検索、後方一致検索、完全一致検索が変化
		#self.searchはbook.rbに記入

		if params[:search] && params[:search_model] == "1"
			@books = Book.search(params[:search], params[:search_way])

		elsif params[:search] && params[:search_model] == "2"
			@users = User.search(params[:search], params[:search_way])
			render template: "users/index"

		else
			@books = Book.all
		end


		#検索履歴を保存
		if params[:search] && params[:order] == nil
			@history = current_user.search_histories.new
			@history.history = params[:search]
			@history.save!
		end

		#検索結果を非同期でソート
		if params[:order] && params[:order] == "1"
			@books_sort = @books.order("id")
			render :sort
		elsif params[:order] && params[:order] == "2"
			@books_sort = @books.order("title")
			render :sort
		end
	end

	def create
		@books = Book.all
		@book = Book.new(book_params)
		@book.user_id = current_user.id
		if @book.save
			redirect_to book_path(@book.id)
		else
			render :new
		end
	end

	def show
  		@book = Book.new
		@books = Book.find(params[:id])
		@post_comment = PostComment.new
	end

	def edit
		@book = Book.find(params[:id])
		if @book.user != current_user
     	   redirect_to books_path
    	end
	end

	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
			flash[:notice] = "Book was successfully updated"
			redirect_to book_path(@book.id)
		else
			render :edit
		end
	end

	def destroy
		book = Book.find(params[:id])
		book.destroy
		redirect_to books_path
	end

	private
	def book_params
		params.require(:book).permit(:title, :body)
	end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_books_index.html.erb
<div class="col-lg-9">
	<h1>Books</h1>
	<table class="table">
		<tr>
			<th>投稿者</th>
			<th>Title</th>
			<th>opinion</th>
		</tr>

<div class="book_index">
<% books.each do |book| %>
		<tr>
			<th>
				<%=link_to user_path(book.user) do %>
					<%= attachment_image_tag book.user, :profile_image,　format: 'jpeg', size: "40x40", fallback: "img/no_image.jpg" %>
				<% end %>
			</th>
			<th><%=link_to book.title, book_path(book.id) %></th>
			<th><%= book.body %></th>
			<th>
				<i class="fa fa-thumbs-up fa-2x"></i>
      			<%= book.favorites.count %>いいね
			</th>
		</tr>
<% end %>
</div>
	</table>
</div>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
   <h2>error</h2>
<% end %>

<div class="container">
<div class="row">

<div class="mx-auto">
<h1>Editing Book</h1>
	<%= form_for(@book) do |f| %>
<h4>Title</h4>
	<%=f.text_field :title %>
<h4>Opinion</h4>
	<%=f.text_area :body %> <br>

	<%=f.submit 'Update Book', class:"btn btn-primary" %>
	<% end %>

	<%=link_to "Show", book_path(@book) %>
	<%=link_to "Back", books_path %>
</div>
</div>

</div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
   <h2>error</h2>
<% end %>
<%= render 'layouts/flash_messages' %>


<div class="container">
<div class="row">

<div class="col-lg-3">

	<div>
		<h3>検索</h3>
		<%= form_tag(books_path, :method => 'get') do %>
		<%= select_tag 'search_model', options_for_select({本のタイトルで検索: 1, ユーザー名で検索: 2}) %>
		<%= select_tag 'search_way', options_for_select({部分一致: 1, 前方一致: 2, 後方一致: 3, 完全一致: 4}) %>
		<%= text_field_tag :search %>
		<%= submit_tag '検索' %>
		<% end %>
	</div>


	<h1>User info</h1>
	<%= attachment_image_tag current_user, :profile_image,　format: 'jpeg', size: "100x100", fallback: "img/no_image.jpg" %>

<table class="table table-striped">
	<tr>
		<th>name</th>
		<th><%= current_user.name %></th>
	</tr>
	<tr>
		<th>introduction</th>
		<th><%= current_user.introduction %></th>
	</tr>

	<tr>
		<th>
			<i class="fas fa-male fa-2x"></i>
			<%= link_to "#{current_user.followings.count}  Following", follows_user_path(current_user.id) %>
		</th>
	</tr>
	<tr>
		<th>
			<i class="fas fa-male fa-2x"></i>
			<%= link_to "#{current_user.followers.count} Followers", followers_user_path(current_user.id) %>
		</th>
	</tr>
</table>

<%= link_to "プロフィール編集", edit_user_path(current_user) %>


<h1>New Book</h1>
	<%= form_for(@book) do |f| %>
<h4>Title</h4>
	<%=f.text_field :title %>
<h4>Opinion</h4>
	<%=f.text_area :body %> <br>

	<%=f.submit 'Create Book', class:"btn btn-primary" %>
	<% end %>


</div>


<div id="search_order">
	<h4>並び替え</h4>
	<%= form_tag(books_path, method: :get, remote: true) do %>
		<%= hidden_field_tag 'search', params[:search] %>
		<%= hidden_field_tag 'search_way', params[:search_way] %>
		<%= hidden_field_tag 'search_model', params[:search_model] %>
		<%= select_tag 'order', options_for_select({日時で並び替え: 1, 五十音で並び替え: 2}) %>
		<%= submit_tag '並び替え' %>
	<% end %>
</div>
<div id="books_index">
	<%= render 'books_index', books: @books %>
</div>


</div>
</div>

app/views/books/show.html.erb
<% if flash[:notice] %>
	<div class="flash">
     	<%= flash[:notice] %>
    </div>
<% end %>

<div class="container">
<div class="row">

<div class="col-lg-3">
	<h1>User info</h1>
	<%= attachment_image_tag @books.user, :profile_image,　format: 'jpeg', size: "100x100", fallback: "img/no_image.jpg" %>

<table class="table table-striped">
	<tr>
		<th>name</th>
		<th><%= @books.user.name %></th>
	</tr>
	<tr>
		<th>introduction</th>
		<th><%= @books.user.introduction %></th>
	</tr>

	<tr>
		<th>
			<i class="fas fa-male fa-2x"></i>
			<%= link_to "#{@books.user.followings.count}  Following", follows_user_path(@books.user.id) %>
		</th>
	</tr>
	<tr>
		<th>
			<i class="fas fa-male fa-2x"></i>
			<%= link_to "#{@books.user.followers.count} Followers", followers_user_path(@books.user.id) %>
		</th>
	</tr>
</table>

<% if @books.user == current_user %>
<%= link_to "プロフィール編集", edit_user_path(@books.user) %>
<% else %>
<%= link_to "プロフィール編集", user_path(current_user.id) %>
<% end %>


<h1>New Book</h1>
	<%= form_for(@book) do |f| %>

<h4>Title</h4>
	<%=f.text_field :title %>
<h4>Opinion</h4>
	<%=f.text_area :body %> <br>

	<%=f.submit 'Create Book', class:"btn btn-primary" %>
	<% end %>

</div>




<div class="col-lg-9">
	<h1>Book detail</h1>
	<table class="table">
		<tr>
			<th>
				<%= attachment_image_tag @books.user, :profile_image,　format: 'jpeg', size: "100x100" %>
				<%=link_to @books.user.name, user_path(@books.user.id) %>
			</th>
			<th><%= @books.title %></th>
			<th><%= @books.body %></th>

			<% if @books.user.id == current_user.id %>
			<th><%=link_to "Edit", edit_book_path(@books.id), class: "btn btn-success btn-xs" %></th>
			<th><%=link_to "Destroy", book_path(@books.id), method: :delete, 'data-confirm' => "本当に削除しますか？", class: "btn btn-danger btn-xs" %></th>
			<% end %>
		</tr>

	</table>
	<div id="favorite_area">
		<%= render "favorites/like", books: @books %>
	</div>

	<h3>Book comment</h3>
	<table class="table">
		<% @books.post_comments.each do |c| %>
		<tr>
			<th><%= c.user.name %></th>
			<th><%= c.comment%></th>

			<th>
				<% if c.user_id == current_user.id %>

				<%=link_to "コメント編集", edit_book_post_comment_path(@books.id, c.id), class: "btn btn-primary btn-xs" %>

				<%=link_to "コメント削除", book_post_comment_path(@books.id, c.id), method: :delete, 'data-confirm' => "ほんまに？", class: "btn btn-danger btn-xs" %>

				<% end %>
			</th>
		</tr>
		<% end %>
	</table>

		<div>
			<%= form_for [@books, @post_comment] do |f| %>
            <%= f.text_area :comment,placeholder: "コメントをここに"%>
    		<%= f.submit "送信する", class: "btn btn-m btn-base-1 mt-20" %>
			<% end %>
		</div>

</div>

</div>
</div>

app/views/books/sort.js.erb
$("#books_index").html("<%= j(render 'books_index', { books: @books_sort }) %>")